# Generated by Django 5.2.5 on 2025-08-12 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='The IP address of the client making the request', verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the request was made', verbose_name='Timestamp')),
                ('path', models.CharField(help_text='The URL path that was requested', max_length=500, verbose_name='Request Path')),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address'], name='ip_tracking_ip_addr_3489f7_idx'), models.Index(fields=['timestamp'], name='ip_tracking_timesta_b1bb90_idx'), models.Index(fields=['path'], name='ip_tracking_path_65894f_idx')],
            },
        ),
    ]
