# Generated by Django 5.2.5 on 2025-08-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0002_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='city',
            field=models.CharField(blank=True, help_text='City from geolocation', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='country',
            field=models.CharField(blank=True, help_text='Country from geolocation', max_length=100, null=True, verbose_name='Country'),
        ),
    ]
