# Generated by Django 5.2.5 on 2025-08-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0003_requestlog_city_requestlog_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='The suspicious IP address', verbose_name='IP Address')),
                ('reason', models.CharField(help_text='Reason why this IP was flagged as suspicious', max_length=500, verbose_name='Reason')),
                ('flagged_at', models.DateTimeField(auto_now_add=True, help_text='When this IP was flagged', verbose_name='Flagged At')),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
                'ordering': ['-flagged_at'],
                'indexes': [models.Index(fields=['ip_address'], name='ip_tracking_ip_addr_11f206_idx'), models.Index(fields=['flagged_at'], name='ip_tracking_flagged_67842b_idx')],
            },
        ),
    ]
